### ISSUE TITLE
很棒的爬虫！

### ISSUE THREAD

**Issue by homeyi** [1oo1/LianjiaCrawler#1]
我昨天试着爬了一下，但程序里没有做模拟登陆的功能，也居然能爬到最新的成交数据，太神奇了。

**Comment by 1oo1** [comment]
谢谢，登陆和不登陆是一样的数据，所以就没有做模拟登陆

**Comment by homeyi** [comment]
嗯，链家现在改版了，以前需要登录才有最新数据。
您这个爬虫程序非常好，我会一直关注，谢谢

**Comment by 1oo1** [comment]
哈哈，很感谢你的认可，国庆节在家无聊学 python 练手玩的，后面暂时没打算更新了

**Comment by homeyi** [comment]
太强了，我都自学python快1年了，也就只能写几行简单的代码
